### ISSUE TITLE
angular images

### ISSUE THREAD

**Issue by mmasriera** [Samitier/dhis2-hii#1]
intenta als tags `<img>`fer servir ng-src en comptes de src. Crec que no ho tens a ningun path encara, però si li poses una expressió Angular no et funcionarà

``` html
<img src="/images/status-{{$scope.currentStatus}}.png" ></img>
```

això no et carregaria la imatge per exemple, si pots posa sempre ng-src i així n otindras problemes

**Comment by mmasriera** [comment]
https://docs.angularjs.org/api/ng/directive/ngSrc

**Comment by Samitier** [comment]
es veritat, que carregava els src abans que angular li dones temps de fer les coses o algo axi...bueno en principi les imatges que hi ha ara no les he de tocar mai, pero per les que venen ja ho tindré en compte, merci.
